services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: moodify_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend/chatbot-frontend
      dockerfile: Dockerfile
    container_name: moodify_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
    depends_on:
      - backend